// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqipgqntsxonbnagjios.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxaXBncW50c3hvbmJuYWdqaW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMjM4MzgsImV4cCI6MjA1MTg5OTgzOH0.g4--swbgAf-hZP6ixlfSsjSRSzbcI1eVQqhO4Wd4Pr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);